name: gwas
channels:
  - conda-forge
dependencies:
  - conda-forge::beautifulsoup4=4.8.0
  - conda-forge::ipykernel=5.1.2
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::nb_conda_kernels=2.2.2
  - conda-forge::notebook=6.0.1
  - conda-forge::numpy=1.17.2
  - conda-forge::pandas=0.25.1
  - conda-forge::python=3.7.3
  - conda-forge::requests=2.22.0
  - conda-forge::scikit-learn=0.21.3
  - conda-forge::scipy=1.3.1
  - conda-forge::tqdm=4.36.1
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-tidyverse=1.2.1
  - conda-forge::r-irkernel=0.8.15
  - conda-forge::r-ggextra=0.9
  - conda-forge::r-cowplot=1.0.0
  - conda-forge::r-venndiagram=1.6.20
  - bioconda::bioconductor-fgsea
  - bioconda::bioconductor-topgo
